SELECT BANNER FROM V$VERSION;	-- Oracle installed version
SHOW USER;		-- connected user, user needs to be sys
SELECT NAME,CON_ID FROM V$PDBS; 	--Shows available pluggable dbs
SELECT NAME AS "SERVICE NAME" FROM V$ACTIVE_SERVICES WHERE CON_ID=3;	

ALTER PLUGGABLE DATABASE College_PDB_STG CLOSE IMMEDIATE;
ALTER PLUGGABLE DATABASE College_PDB_STG UNPLUG INTO 'D:\ORACLE\ORADATA\College_PDB_STG.xml';
DROP PLUGGABLE DATABASE College_PDB_STG INCLUDING DATAFILES;

CREATE PLUGGABLE DATABASE College_PDB_STG
  ADMIN USER pdbadmin IDENTIFIED BY PdbAdmin#123
  ROLES = (DBA)
  FILE_NAME_CONVERT = ('D:\ORACLE_21C\ORADATA\ORCL\PDBSEED\', 'D:\ORACLE\ORADATA\College_PDB_STG\');

ALTER PLUGGABLE DATABASE College_PDB_STG OPEN;
ALTER PLUGGABLE DATABASE College_PDB_STG SAVE STATE;

show pdbs;
SELECT NAME FROM V$SERVICES;
